// frontend/src/components/form/Input.vue
<script setup lang="ts">
import { ComponentPublicInstance, computed, nextTick, ref, useCssModule, watch } from "vue"
import { KeyEvent, KeyPress, toKeyEvent, useInterceptedKey, useKeyDeclaration, USUAL_PRIMITIVE_KEY_VALIDATORS } from "@/modules/keyboard"

const props = defineProps<{
    value?: string | null | undefined
    placeholder?: string
    type?: "text" | "password" | "number" | "textarea"
    size?: "small" | "std" | "large"
    width?: "one-third" | "half" | "three-quarter" | "std" | "medium" | "large" | "2x" | "3x" | "25" | "50" | "75" | "fullwidth"
    disabled?: boolean
    autoFocus?: boolean
    updateOnInput?: boolean
    focusOnKeypress?: KeyPress
}>()

const emit = defineEmits<{
    (e: "update:value", value: string): void
    (e: "keypress", event: KeyEvent): void
    (e: "enter", event: KeyEvent): void
}>()

watch(() => props.value, () => { value.value = props.value ?? "" })

const value = ref(props.value ?? "")

const onUpdate = (e: InputEvent) => {
    value.value = (e.target as HTMLInputElement).value
    emit("update:value", value.value)
}

//按键事件处理
const keyDeclaration = useKeyDeclaration()

//对于Enter按键，有一个快捷事件作响应

const onKeydown = (e: KeyboardEvent) => {
    if(!composition) {
        if(!keyDeclaration.primitiveValidator(e)) {
            e.stopPropagation()
            e.stopImmediatePropagation()
        }
        const keyEvent = toKeyEvent(e)
        emit("keypress", keyEvent)
        if(USUAL_PRIMITIVE_KEY_VALIDATORS.Enter(e)) {
            emit("enter", keyEvent)
        }
    }
}

//输入法合成器防抖
let composition = false
const onCompositionstart = () => composition = true
const onCompositionend = () => composition = false

//聚焦用ref
let inputRef: HTMLInputElement | null = null

//按键时聚焦
if(props.focusOnKeypress) useInterceptedKey(props.focusOnKeypress, () => inputRef?.focus())

//挂载ref回调
const mountedCallback = (props.focusOnKeypress || props.autoFocus || undefined) && async function(el: Element | ComponentPublicInstance | null) {
    const ref = (el as HTMLInputElement | null)
    if(props.focusOnKeypress) inputRef = ref
    if(props.autoFocus && ref) {
        await nextTick()
        ref.focus()
    }
}

const events = {[props.updateOnInput ? "onInput" : "onChange"]: onUpdate, onKeydown, onCompositionstart, onCompositionend}

const style = useCssModule()

const inputClass = computed(() => [
    style.input,
    style[`is-size-${props.size ?? "std"}`],
    props.width ? style[`is-width-${props.width}`] : null
])

</script>

<template>
    <component
        :is="type === 'textarea' ? 'textarea' : 'input'"
        :type="type !== 'textarea' ? (type ?? 'text') : undefined"
        :ref="mountedCallback" :class="inputClass" v-bind="events"
        :disabled="disabled" :placeholder="placeholder" :value="value"
    />
</template>

<style module lang="sass">
@import "../../styles/base/size"
@import "../../styles/base/color"

.input
    vertical-align: top
    align-items: center
    display: inline-flex
    line-height: 1.2
    padding: 0 calc(0.85em - 1px)
    border-radius: $radius-size-std
    border: 1px solid $light-mode-border-color
    color: $light-mode-text-color
    background-color: $light-mode-block-color
    &[disabled]
        color: mix($light-mode-text-color, #ffffff, 20)
        background-color: mix($light-mode-block-color, #000000, 96)
    @media (prefers-color-scheme: dark)
        border-color: $dark-mode-border-color
        color: $dark-mode-text-color
        background-color: $dark-mode-block-color
        &[disabled]
            color: mix($dark-mode-text-color, #000000, 20)
            background-color: mix($dark-mode-block-color, #FFFFFF, 96)

textarea.input
    $textarea-max-height: 40em !default
    $textarea-min-height: 8em !default
    padding: calc(0.6em - 1px) calc(0.85em - 1px)
    resize: vertical
    &:not([rows])
        max-height: $textarea-max-height
        min-height: $textarea-min-height
    &[rows]
        height: initial

.is-size-small
    font-size: $font-size-small
    height: $element-height-small
.is-size-std
    font-size: $font-size-std
    height: $element-height-std
.is-size-large
    font-size: $font-size-large
    height: $element-height-large

@each $name, $size in ("one-third" 0.333em, "half" 0.5em, "three-quarter" 0.75em, "std" 1em, "medium" 1.25em, "large" 1.5em, "2x" 2em, "3x" 3em)
    .is-width-#{$name}
        width: #{$size * 13.6}
        max-width: #{$size * 13.6}
@each $name, $size in ("25" 0.25, "50" 0.5, "75" 0.75, "fullwidth" 1)
    .is-width-#{$name}
        width: percentage($size)
        max-width: percentage($size)

</style>

// crx/src/components/form/Input.tsx
import React, { useEffect, useRef, useState } from "react"
import { mix } from "polished"
import { styled, css } from "styled-components"
import { useWatch } from "@/utils/reactivity"
import { DARK_MODE_COLORS, ELEMENT_HEIGHTS, FONT_SIZES, FunctionalColors, LIGHT_MODE_COLORS, RADIUS_SIZES, ThemeColors } from "@/styles"
import { dates } from "@/utils/primitives"

interface InputProps {
    value?: string | null | undefined
    type?: "text" | "password" | "number" | "textarea"
    size?: "small" | "std" | "large"
    textAlign?: "left" | "center" | "right"
    maxHeight?: string
    minHeight?: string
    rows?: number
    theme?: "std" | "underline"
    borderColor?: ThemeColors | FunctionalColors
    width?: string
    placeholder?: string
    disabled?: boolean
    updateOnInput?: boolean
    autoFocus?: boolean
    onUpdateValue?(value: string): void
    onKeydown?(e: React.KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>): void
    onEnter?(e: React.KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>): void
    onBlur?(e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>): void
    onFocus?(e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>): void
}

interface DateInputProps {
    value?: Date
    onUpdateValue?(value: Date | undefined): void
    mode?: "date" | "datetime"
    theme?: "std" | "underline"
    placeholder?: string
    borderColor?: ThemeColors | FunctionalColors
    errorBorderColor?: ThemeColors | FunctionalColors
    size?: "small" | "std" | "large"
    textAlign?: "left" | "center" | "right"
    width?: string
    disabled?: boolean
    autoFocus?: boolean
}

export const Input = React.forwardRef(function (props: InputProps, ref: React.ForwardedRef<HTMLElement>) {
    const { type, size, width, textAlign, theme, borderColor, placeholder, disabled, value, onUpdateValue } = props

    //输入法合成器防抖
    const compositionRef = useRef(false)
    const onCompositionstart = () => compositionRef.current = true
    const onCompositionend = () => compositionRef.current = false

    //自动聚焦
    const localRef = useRef<HTMLElement | null>(undefined)
    const setRef = (el: HTMLInputElement | HTMLTextAreaElement | null) => {
        if(ref !== null) {
            if(typeof ref === "function") ref(el)
            else ref.current = el
        }
        if(props.autoFocus) {
            localRef.current = el
        }
    }
    if(props.autoFocus) {
        // eslint-disable-next-line react-hooks/rules-of-hooks
        useEffect(() => { localRef.current?.focus() }, [])
    }

    if(props.updateOnInput) {
        const onChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onUpdateValue?.(e.target.value)

        const onKeydown = (e: React.KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) => {
            if(!compositionRef.current) {
                props.onKeydown?.(e)
                if(e.code === "Enter" && !e.ctrlKey && !e.altKey) {
                    props.onEnter?.(e)
                }
            }
        }
    
        if(type === "textarea") {
            return <StyledTextarea ref={setRef} 
                $size={size ?? "std"} $width={width} $textAlign={textAlign} $theme={theme} $borderColor={borderColor}
                $maxHeight={props.maxHeight} $minHeight={props.minHeight} rows={props.rows}
                disabled={disabled} placeholder={placeholder} value={value ?? undefined} 
                onChange={onChange} onKeyDown={onKeydown} onBlur={props.onBlur} onFocus={props.onFocus}
                onCompositionStart={onCompositionstart} onCompositionEnd={onCompositionend}/>
        }else{
            return <StyledInput ref={setRef} 
                $size={size ?? "std"} $width={width} $textAlign={textAlign} $theme={theme} $borderColor={borderColor}
                type={type ?? "text"} disabled={disabled} placeholder={placeholder} value={value ?? undefined} 
                onChange={onChange} onKeyDown={onKeydown} onBlur={props.onBlur} onFocus={props.onFocus}
                onCompositionStart={onCompositionstart} onCompositionEnd={onCompositionend}/>
        }
    }else{
        // eslint-disable-next-line react-hooks/rules-of-hooks
        const [text, setText] = useState<string>(props.value ?? "")

        // eslint-disable-next-line react-hooks/rules-of-hooks
        useWatch(() => setText(props.value ?? ""), [props.value ?? ""])

        const onChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setText(e.target.value)

        const onKeydown = (e: React.KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) => {
            if(!compositionRef.current) {
                props.onKeydown?.(e)
                if(e.code === "Enter" && !e.ctrlKey && !e.altKey) {
                    props.onEnter?.(e)
                    //在按下Enter时，主动触发updateValue
                    if(type !== "textarea") props.onUpdateValue?.(text)
                }
            }
        }
    
        const onBlur = (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => {
            onUpdateValue?.(text)
            props.onBlur?.(e)
        }

        if(type === "textarea") {
            return <StyledTextarea ref={setRef} 
                $size={size ?? "std"} $width={width} $textAlign={textAlign} $theme={theme} $borderColor={borderColor}
                $maxHeight={props.maxHeight} $minHeight={props.minHeight} rows={props.rows}
                disabled={disabled} placeholder={placeholder} value={text} 
                onChange={onChange} onBlur={onBlur} onKeyDown={onKeydown} 
                onCompositionStart={onCompositionstart} onCompositionEnd={onCompositionend}/>
        }else{
            return <StyledInput ref={setRef} 
                $size={size ?? "std"} type={type ?? "text"} $width={width} $textAlign={textAlign} $theme={theme} $borderColor={borderColor}
                disabled={disabled} placeholder={placeholder} value={text} 
                onChange={onChange} onBlur={onBlur} onKeyDown={onKeydown} 
                onCompositionStart={onCompositionstart} onCompositionEnd={onCompositionend}/>
        }
    }
})

export const DateInput = React.memo(function (props: DateInputProps) {
    const { value, onUpdateValue, mode = "datetime", placeholder = mode === "date" ? "YYYY-MM-DD" : "YYYY-MM-DD HH:mm:SS", borderColor, errorBorderColor = "danger", ...attrs } = props

    const [text, setText] = useState(() => value !== undefined ? (mode === "date" ? dates.toFormatDate(value) : dates.toFormatDateTime(value)) : "")

    const [error, setError] = useState(false)

    useWatch(() => setText(value !== undefined ? (mode === "date" ? dates.toFormatDate(value) : dates.toFormatDateTime(value)) : ""), [value])

    const submitValue = () => {
        const trimed = text.trim()
        if("today" === trimed.toLowerCase()) {
            props.onUpdateValue?.(mode === "date" ? new Date() : new Date(new Date().setHours(0, 0, 0, 0)))
            if(error) setError(false)
        }else if(trimed) {
            const d = mode === "date" ? new Date(`${trimed} 00:00:00`) : new Date(trimed)
            if(isNaN(d.getTime())) {
                if(!error) setError(true)
            }else{
                props.onUpdateValue?.(d)
                if(error) setError(false)
            }
        }else{
            props.onUpdateValue?.(undefined)
        }
    }

    return <Input {...attrs} placeholder={placeholder} borderColor={error ? errorBorderColor : borderColor} value={text} onUpdateValue={setText} onBlur={submitValue} onEnter={submitValue} updateOnInput/>
})

interface StyledCSSProps {
    $size: "small" | "std" | "large"
    $width?: string
    $textAlign?: "left" | "center" | "right"
    $theme?: "std" | "underline"
    $borderColor?: ThemeColors | FunctionalColors
}

interface TextareaProps {
    $maxHeight?: string
    $minHeight?: string
}

const StyledCSS = css<StyledCSSProps>`
    text-rendering: auto;
    letter-spacing: normal;
    word-spacing: normal;
    text-transform: none;
    text-indent: 0;
    text-shadow: none;
    justify-content: flex-start;
    -webkit-rtl-ordering: logical;
    box-sizing: border-box;
    outline: none;
    vertical-align: middle;
    align-items: center;
    display: inline-flex;
    line-height: 1.2;
    color: ${LIGHT_MODE_COLORS["text"]};
    font-size: ${p => FONT_SIZES[p.$size]};
    height: ${p => ELEMENT_HEIGHTS[p.$size]};
    ${p => p.$textAlign && css`text-align: ${p.$textAlign};`}
    ${p => p.$width && css` width: ${() => p.$width}; `}
    ${p => p.$theme === "underline" ? css`
        border-top-right-radius: ${RADIUS_SIZES["std"]};
        border-top-left-radius: ${RADIUS_SIZES["std"]};
        border-width: 0 0 1px 0;
        border-style: solid;
        border-color: ${LIGHT_MODE_COLORS[p.$borderColor ?? "border"]};
        background-color: transparent;
        &:focus {
            background-color: rgba(0, 0, 0, 0.03);
        }
        &[disabled] {
            color: ${mix(0.2, LIGHT_MODE_COLORS["text"], "#ffffff")};
        }
        @media (prefers-color-scheme: dark) {
            color: ${DARK_MODE_COLORS["text"]};
            border-bottom-color: ${DARK_MODE_COLORS[p.$borderColor ?? "border"]};
            &:focus {
                background-color: rgba(255, 255, 255, 0.04);
            }
        }
    ` : css`
        border-radius: ${RADIUS_SIZES["std"]};
        border: 1px solid ${LIGHT_MODE_COLORS[p.$borderColor ?? "border"]};
        background-color: ${LIGHT_MODE_COLORS["block"]};
        &[disabled] {
            color: ${mix(0.2, LIGHT_MODE_COLORS["text"], "#ffffff")};
            background-color: ${mix(0.96, LIGHT_MODE_COLORS["block"], "#000000")};
        }
        @media (prefers-color-scheme: dark) {
            color: ${DARK_MODE_COLORS["text"]};
            background-color: ${DARK_MODE_COLORS["block"]};
            border-color: ${DARK_MODE_COLORS[p.$borderColor ?? "border"]};
            &[disabled] {
                color: ${mix(0.2, DARK_MODE_COLORS["text"], "#ffffff")};
                background-color: m${mix(0.96, DARK_MODE_COLORS["block"], "#000000")};
            }
        }
    `}
`

const StyledInput = styled.input<StyledCSSProps>`
    ${StyledCSS};
    padding: 0 calc(0.85em - 1px);
    &::-webkit-outer-spin-button, 
    &::-webkit-inner-spin-button {
        -webkit-appearance: none;
    }
`

const StyledTextarea = styled.textarea<StyledCSSProps & TextareaProps>`
    ${StyledCSS};
    padding: calc(0.6em - 1px) calc(0.85em - 1px);
    resize: vertical;
    &:not([rows]) {
        max-height: ${p => p.$maxHeight ?? "40em"};
        min-height: ${p => p.$minHeight ?? "6em"};
    }
    &[rows] {
        height: initial;
        ${p => p.$maxHeight && css`max-height: ${p.$maxHeight};`}
        ${p => p.$minHeight && css`min-height: ${p.$minHeight};`}
    }
`
